name: dtiled
version: 0.0.7
author: Darren Reid <layoric@gmail.com>
description: A library to help render Tiled map editor maps.
homepage: https://github.com/Layoric/DTiled
documentation: https://github.com/Layoric/DTiled/wiki
dependencies:
  browser: '>=0.9.0 <0.9.1'
